let all_cities = [
  { label: 'Please select your city', value: 'Please select your city' },
  { label: 'Herat', value: 'Herat' },
  { label: 'Kabul', value: 'Kabul' },
  { label: 'Kandahar', value: 'Kandahar' },
  { label: 'Molah', value: 'Molah' },
  { label: 'Rana', value: 'Rana' },
  { label: 'Shar', value: 'Shar' },
  { label: 'Sharif', value: 'Sharif' },
  { label: 'Wazir Akbar Khan', value: 'Wazir Akbar Khan' },
  { label: 'Elbasan', value: 'Elbasan'},
  { label: 'Petran', value: 'Petran'},
  { label: 'Pogradec', value: 'Pogradec' },
  { label: 'Shkoder', value: 'Shkoder' },
  { label: 'Tirana', value: 'Tirana' },
  { label: 'Ura Vajgurore', value: 'Ura Vajgurore' },
  { label: 'Algiers', value: 'Algiers' },
  { label: 'Annaba', value: 'Annaba' },
  { label: 'Algiers', value: 'Algiers' },
  { label: 'Annaba', value: 'Annaba' },
  { label: 'Azazga', value: 'Azazga' },
  { label: 'Batna City', value: 'Batna City' },
  { label: 'Blida', value: 'Blida' },
  { label: 'Bordj', value: 'Bordj' },
  { label: 'Bordj Bou Arreridj', value: 'Bordj Bou Arreridj' },
  { label: 'Bougara', value: 'Bougara' },
  { label: 'Cheraga', value: 'Cheraga' },
  { label: 'Chlef', value: 'Chlef' },
  { label: 'Constantine', value: 'Constantine' },
  { label: 'Djelfa', value: 'Djelfa' },
  { label: 'Draria', value: 'Draria' },
  { label: 'El Tarf', value: 'El Tarf' },
  { label: 'Hussein Dey', value: 'Hussein Dey' },
  { label: 'Illizi', value: 'Illizi' },
  { label: 'Jijel', value: 'Jijel' },
  { label: 'Kouba', value: 'Kouba' },
  { label: 'Laghouat', value: 'Laghouat' },
  { label: 'Oran', value: 'Oran' },
  { label: 'Ouargla', value: 'Ouargla' },
  { label: 'Oued Smar', value: 'Oued Smar' },
  { label: 'Relizane', value: 'Relizane' },
  { label: 'Rouiba', value: 'Rouiba' },
  { label: 'Saida', value: 'Saida' },
  { label: 'Souk Ahras', value: 'Souk Ahras' },
  { label: 'Tamanghasset', value: 'Tamanghasset' },
  { label: 'Tiaret', value: 'Tiaret' },
  { label: 'Tissemsilt', value: 'Tissemsilt' },
  { label: 'Tizi', value: 'Tizi' },
  { label: 'Tizi Ouzou', value: 'Tizi Ouzou' },
  { label: 'Tlemcen', value: 'Tlemcen' },
  { label: 'Andorra la Vella', value: 'Andorra la Vella' },
  { label: 'Canillo', value: 'Canillo' },
  { label: 'Encamp', value: 'Encamp' },
  { label: 'Engordany', value: 'Engordany' },
  { label: 'Escaldes-Engordany', value: 'Escaldes-Engordany' },
  { label: 'La Massana', value: 'La Massana' },
  { label: 'Llorts', value: 'Llorts' },
  { label: 'Ordino', value: 'Ordino' },
  { label: 'Santa Coloma', value: 'Santa Coloma' },
  { label: 'Sispony', value: 'Sispony' },
  { label: 'Soldeu', value: 'Soldeu' },
  { label: 'Ambriz', value: 'Ambriz' },
  { label: 'Benguela', value: 'Benguela' },
  { label: 'Cabinda', value: 'Cabinda' },
  { label: 'Cacole', value: 'Cacole' },
  { label: 'Camabatela', value: 'Camabatela' },
  { label: 'Cazeta', value: 'Cazeta' },
  { label: 'Huambo', value: 'Huambo' },
  { label: 'Kuito', value: 'Kuito' },
  { label: 'Lobito', value: 'Lobito' },
  { label: 'Luanda', value: 'Luanda' },
  { label: 'Lubango', value: 'Lubango' },
  { label: 'Lucapa', value: 'Lucapa' },
  { label: 'Lumeje', value: 'Lumeje' },
  { label: 'Malanje', value: 'Malanje' },
  { label: 'Menongue', value: 'Menongue' },
  { label: 'Muxaluando', value: 'Muxaluando' },
  { label: 'Namibe', value: 'Namibe' },
  { label: 'Ondjiva', value: 'Ondjiva' },
  { label: 'Piri', value: 'Piri' },
  { label: 'Saurimo', value: 'Saurimo' },
  { label: 'Talatona', value: 'Talatona' },
  { label: 'All Saints', value: 'All Saints' },
  { label: 'Cassada Gardens', value: 'Cassada Gardens' },
  { label: 'Codrington', value: 'Codrington' },
  { label: 'Old Road', value: 'Old Road' },
  { label: 'Parham', value: 'Parham' },
  { label: 'Woods', value: 'Woods' },
  { label: '28 de Noviembre', value: '28 de Noviembre' },
{ label: 'Abasto', value: 'Abasto' },
{ label: 'Acassuso', value: 'Acassuso' },
{ label: 'Acebal', value: 'Acebal' },
{ label: 'Acevedo', value:'Acevedo' },
{ label: 'Adelia Maria', value: 'Adelia Maria' },
{ label: 'Agua de Oro', value: 'Agua de Oro' },
{ label: 'Albardon', value: 'Albardon'},
{ label: 'Albarellos', value: 'Albarellos'},
{ label: 'Alberdi', value: 'Alberdi' },
{ label: 'Alberti', value: 'Alberti' },
{ label: 'Aldo Bonzi', value: 'Aldo Bonzi' },
{ label: 'Alejandro Korn', value: 'Alejandro Korn' },
{ label: 'Alicia', value: 'Alicia' },
{ label: 'Allen', value: 'Allen' },
{ label: 'Almafuerte', value: 'Almafuerte' },
{ label: 'Almagro', value: 'Almagro' },
{ label: 'Almirante Brown', value: 'Almirante Brown' },
{ label: 'Alta Gracia', value: 'Alta Gracia' },
{ label: 'Alta Italia', value: 'Alta Italia' },
{ label: 'Alvarez', value: 'Alvarez' },
{ label: 'Alvear', value: 'Alvear' },
{ label: 'Anatuya', value: 'Anatuya' },
{ label: 'Angelica', value: 'Angelica' },
{ label: 'Antonio Carboni', value: 'Antonio Carboni' },
{ label: 'Apostoles', value: 'Apostoles' },
{ label: 'Arequito', value: 'Arequito' },
{ label: 'Armstrong', value: 'Armstrong' },
{ label: 'Arrecifes', value: 'Arrecifes' },
{ label: 'Arroyito', value: 'Arroyito' },
{ label: 'Arroyito', value: 'Arroyito' },
{ label: 'Arroyito Challaco', value: 'Arroyito Challaco' },
{ label: 'Arroyo Seco', value: 'Arroyo Seco' },
{ label: 'Arteaga', value: 'Arteaga' },
{ label: 'Asamblea', value: 'Asamblea' },
{ label: 'Ascension', value: 'Ascension' },
{ label: 'Avellaneda', value: 'Avellaneda' },
{ label: 'Avellaneda', value: 'Avellaneda' },
{ label: 'Ayacucho', value: 'Ayacucho' },
{ label: 'Azara', value: 'Azara' },
{ label: 'Azul', value: 'Azul' },
{ label: 'Balcarce', value: 'Balcarce' },
{ label: 'Balnearia', value: 'Balnearia' },
{ label: 'Banda del Rio Sali', value: 'Banda del Rio Sali' },
{ label: 'Bandera', value: 'Bandera' },
{ label: 'Banfield', value: 'Banfield' },
{ label: 'Baradero', value: 'Baradero' },
{ label: 'Bariloche', value: 'Bariloche' },
{ label: 'Barrio Fisherton', value: 'Barrio Fisherton' },
{ label: 'Batan', value: 'Batan' },
{ label: 'Beccar', value: 'Beccar' },
{ label: 'Belen de Escobar', value: 'Belen de Escobar' },
{ label: 'Belgrano', value: 'Belgrano' },
{ label: 'Belgrano', value: 'Belgrano' },
{ label: 'Bell Ville', value: 'Bell Ville' },
{ label: 'Bella Vista', value: 'Bella Vista' },
{ label: 'Bella Vista', value: 'Bella Vista' },
{ label: 'Benavidez', value: 'Benavidez' },
{ label: 'Berazategui', value: 'Berazategui' },
{ label: 'Berisso', value: 'Berisso' },
{ label: 'Bernal', value: 'Bernal' },
{ label: 'Bernardo Larroude', value: 'Bernardo Larroude' },
{ label: 'Bernasconi', value: 'Bernasconi' },
{ label: 'Bigand', value: 'Bigand' },
{ label: 'Bombal', value: 'Bombal' },
{ label: 'Bordenave', value: 'Bordenave' },
{ label: 'Bosch', value: 'Bosch' },
{ label: 'Bosques', value: 'Bosques' },
{ label: 'Boulogne', value: 'Boulogne' },
{ label: 'Bovril', value: 'Bovril' },
{ label: 'Bragado', value: 'Bragado' },
{ label: 'Brandsen', value: 'Brandsen' },
{ label: 'Brinkmann', value: 'Brinkmann' },
{ label: 'Buenos Aires', value: 'Buenos Aires' },
{ label: 'Burzaco', value: 'Burzaco' },
{ label: 'Bustinza', value: 'Bustinza' },
{ label: 'Caballito', value: 'Caballito' },
{ label: 'Calderon', value: 'Calderon' },
{ label: 'Caleta Olivia', value: 'Caleta Olivia' },
{ label: 'Caleufu', value: 'Caleufu' },
{ label: 'Camilo Aldao', value: 'Camilo Aldao' },
{ label: 'Campana', value: 'Campana' },
{ label: 'Canada de Gomez', value: 'Canada de Gomez' },
{ label: 'Canada del Ucle', value: 'Canada del Ucle' },
{ label: 'Canada Rosquin', value: 'Canada Rosquin' },
{ label: 'Canals', value: 'Canals' },
{ label: 'Canning', value: 'Canning' },
{ label: 'Canuelas', value: 'Canuelas' },
{ label: 'Capilla del Monte', value: 'Capilla del Monte' },
{ label: 'Capilla del Senor', value: 'Capilla del Senor' },
{ label: 'Capitan Bermudez', value: 'Capitan Bermudez' },
{ label: 'Carhue', value: 'Carhue' },
{ label: 'Carlos Casares', value: 'Carlos Casares' },
{ label: 'Carlos Pellegrini', value: 'Carlos Pellegrini' },
{ label: 'Carlos Tejedor', value: 'Carlos Tejedor' },
{ label: 'Caseros', value: 'Caseros' },
{ label: 'Casilda', value: 'Casilda' },
{ label: 'Castelar', value: 'Castelar' },
{ label: 'Castelli', value: 'Castelli' },
{ label: 'Castillo', value: 'Castillo' },
{ label: 'Catriel', value: 'Catriel' },
{ label: 'Catrilo', value: 'Catrilo' },
{ label: 'Cavanagh', value: 'Cavanagh' },
{ label: 'Centenario', value: 'Centenario' },
{ label: 'Ceres', value: 'Ceres' },
{ label: 'Cervantes', value: 'Cervantes' },
{ label: 'Chacabuco', value: 'Chacabuco' },
{ label: 'Chacarita', value: 'Chacarita' },
{ label: 'Chajari', value: 'Chajari' },
{ label: 'Charata', value: 'Charata' },
{ label: 'Chateaubriand', value: 'Chateaubriand' },
{ label: 'Chilecito', value: 'Chilecito' },
{ label: 'Chivilcoy', value: 'Chivilcoy' },
{ label: 'Choele Choel', value: 'Choele Choel' },
{ label: 'Chorroarin', value: 'Chorroarin' },
{ label: 'Cinco Saltos', value: 'Cinco Saltos' },
{ label: 'Cipolletti', value: 'Cipolletti' },
{ label: 'City Bell', value: 'City Bell' },
{ label: 'Ciudad General Belgrano', value: 'Ciudad General Belgrano' },
{ label: 'Ciudadela', value: 'Ciudadela' },
{ label: 'Claypole', value: 'Claypole' },
{ label: 'Clorinda', value: 'Clorinda' },
{ label: 'Colon', value: 'Colon' },
{ label: 'Colon', value: 'Colon' },
{ label: 'Colonia Baron', value: 'Colonia Baron' },
{ label: 'Colonia Caroya', value: 'Colonia Caroya' },
{ label: 'Colonia San Miguel Arcangel', value: 'Colonia San Miguel Arcangel' },
{ label: 'Comodoro Rivadavia', value: 'Comodoro Rivadavia' },
{ label: 'Concepcion', value: 'Concepcion' },
{ label: 'Concepcion', value: 'Concepcion' },
{ label: 'Concordia', value: 'Concordia' },
{ label: 'Constituyentes', value: 'Constituyentes' },
{ label: 'Coronel Dorrego', value: 'Coronel Dorrego' },
{ label: 'Coronel Martinez de Hoz', value: 'Coronel Martinez de Hoz' },
{ label: 'Coronel Pringles', value: 'Coronel Pringles' },
{ label: 'Corral de Bustos', value: 'Corral de Bustos' },
{ label: 'Corralitos', value: 'Corralitos' },
{ label: 'Corrientes', value: 'Corrientes' },
{ label: 'Cosquin', value: 'Cosquin' },
{ label: 'Coy Aike', value: 'Coy Aike' },
{ label: 'Cramer', value: 'Cramer' },
{ label: 'Crespo', value: 'Crespo' },
{ label: 'Cruz del Eje', value: 'Cruz del Eje' },
{ label: 'Curuzu Cuatia', value: 'Curuzu Cuatia' },
{ label: 'Cutral-Co', value: 'Cutral-Co' },
{ label: 'Darregueira', value: 'Darregueira' },
{ label: 'De Mayo', value: 'De Mayo' },
{ label: 'Del Campillo', value: 'Del Campillo' },
{ label: 'Del Viso', value: 'Del Viso' },
{ label: 'Despenaderos', value: 'Despenaderos' },
{ label: 'Devoto', value: 'Devoto' },
{ label: 'Diaz', value: 'Diaz' },
{ label: 'Diego de Alvear', value: 'Diego de Alvear' },
{ label: 'Doblas', value: 'Doblas' },
{ label: 'Dock Sud', value: 'Dock Sud' },
{ label: 'Dolores', value: 'Dolores' },
{ label: 'Don Bosco', value: 'Don Bosco' },
{ label: 'Don Torcuato', value: 'Don Torcuato' },
{ label: 'Drabble', value: 'Drabble' },
{ label: 'Eduardo Castex', value: 'Eduardo Castex' },
{ label: 'El Calafate', value: 'El Calafate' },
{ label: 'El Dorado', value: 'El Dorado' },
{ label: 'El Hoyo', value: 'El Hoyo' },
{ label: 'El Palomar', value: 'El Palomar' },
{ label: 'El Palomar', value: 'El Palomar' },
{ label: 'El Talar', value: 'El Talar' },
{ label: 'El Trebol', value: 'El Trebol' },
{ label: 'Eldorado', value: 'Eldorado' },
{ label: 'Embalse', value: 'Embalse' },
{ label: 'Empalme Lobos', value: 'Empalme Lobos' },
{ label: 'Ensenada', value: 'Ensenada' },
{ label: 'Esperanza', value: 'Esperanza' },
{ label: 'Esquel', value: 'Esquel' },
{ label: 'Esteban Echeverria', value: 'Esteban Echeverria' },
{ label: 'Ezeiza', value: 'Ezeiza' },
{ label: 'Ezpeleta', value: 'Ezpeleta' },
{ label: 'Famailla', value: 'Famailla' },
{ label: 'Fatima', value: 'Fatima' },
{ label: 'Federal', value: 'Federal' },
{ label: 'Fernandez', value: 'Fernandez' },
{ label: 'Firmat', value: 'Firmat' },
{ label: 'Florencio Varela', value: 'Florencio Varela' },
{ label: 'Florentino Ameghino', value: 'Florentino Ameghino' },
{ label: 'Flores', value: 'Flores' },
{ label: 'Floresta', value: 'Floresta' },
{ label: 'Florida', value: 'Florida' },
{ label: 'Formosa', value: 'Formosa' },
{ label: 'Francisco Alvarez', value: 'Francisco Alvarez' },
{ label: 'Franck', value: 'Franck' },
{ label: 'Fray Luis A. Beltran', value: 'Fray Luis A. Beltran' },
{ label: 'Freyre', value: 'Freyre' },
{ label: 'Frias', value: 'Frias' },
{ label: 'Funes', value: 'Funes' },
{ label: 'Gaiman', value: 'Gaiman' },
{ label: 'Galvez', value: 'Galvez' },
{ label: 'Garin', value: 'Garin' },
{ label: 'Garupa', value: 'Garupa' },
{ label: 'General Acha', value: 'General Acha' },
{ label: 'General Alvear', value: 'General Alvear' },
{ label: 'General Cabrera', value: 'General Cabrera' },
{ label: 'General Deheza', value: 'General Deheza' },
{ label: 'General Guido', value: 'General Guido' },
{ label: 'General Juan Madariaga', value: 'General Juan Madariaga' },
{ label: 'General Lagos', value: 'General Lagos' },
{ label: 'General Las Heras', value: 'General Las Heras' },
{ label: 'General Lavalle', value: 'General Lavalle' },
{ label: 'General Mansilla', value: 'General Mansilla' },
{ label: 'General Martin Miguel de Guemes', value: 'General Martin Miguel de Guemes' },
{ label: 'General Pacheco', value: 'General Pacheco' },
{ label: 'General Paz', value: 'General Paz' },
{ label: 'General Pico', value: 'General Pico' },
{ label: 'General Roca', value: 'General Roca' },
{ label: 'General Roca', value: 'General Roca' },
{ label: 'General Rodriguez', value: 'General Rodriguez' },
{ label: 'General San Martin', value: 'General San Martin' },
{ label: 'General San Martin', value: 'General San Martin' },
{ label: 'General Viamonte', value: 'General Viamonte' },
{ label: 'General Villegas', value: 'General Villegas' },
{ label: 'Germania', value: 'Germania' },
{ label: 'Glew', value: 'Glew' },
{ label: 'Gobernador Crespo', value: 'Gobernador Crespo' },
{ label: 'Gobernador Galvez', value: 'Gobernador Galvez' },
{ label: 'Godoy', value: 'Godoy' },
{ label: 'Godoy Cruz', value: 'Godoy Cruz' },
{ label: 'Gonzalez Catan', value: 'Gonzalez Catan' },
{ label: 'Gonzalez Moreno', value: 'Gonzalez Moreno' },
{ label: 'Goya', value: 'Goya' },
{ label: 'Granadero Baigorria', value: 'Granadero Baigorria' },
{ label: 'Grand Bourg', value: 'Grand Bourg' },
{ label: 'Gualeguay', value: 'Gualeguay' },
{ label: 'Guatrache', value: 'Guatrache' },
{ label: 'Guernica', value: 'Guernica' },
{ label: 'Henderson', value: 'Henderson' },
{ label: 'Hernando', value: 'Hernando' },
{ label: 'Hersilia', value: 'Hersilia' },
{ label: 'Hilario', value: 'Hilario' },
{ label: 'Hilario Ascasubi', value: 'Hilario Ascasubi' },
{ label: 'Hipatia', value: 'Hipatia' },
{ label: 'Hipolito Yrigoyen', value: 'Hipolito Yrigoyen' },
{ label: 'Huanchillas', value: 'Huanchillas' },
{ label: 'Huanguelen', value: 'Huanguelen' },
{ label: 'Huinca Renanco', value: 'Huinca Renanco' },
{ label: 'Humahuaca', value: 'Humahuaca' },
{ label: 'Hurlingham', value: 'Hurlingham' },
{ label: 'Ibarlucea', value: 'Ibarlucea' },
{ label: 'Ibicuy', value: 'Ibicuy' },
{ label: 'Independencia', value: 'Independencia' },
{ label: 'Ingeniero Beaugey', value: 'Ingeniero Beaugey' },
{ label: 'Ingeniero Luiggi', value: 'Ingeniero Luiggi' },
{ label: 'Ingeniero Maschwitz', value: 'Ingeniero Maschwitz' },
{ label: 'Intendente Alvear', value: 'Intendente Alvear' },
{ label: 'Isidro Casanova', value: 'Isidro Casanova' },
{ label: 'Ituzaingo', value: 'Ituzaingo' },
{ label: 'James Craik', value: 'James Craik' },
{ label: 'Jauregui', value: 'Jauregui' },
{ label: 'Jeppener', value: 'Jeppener' },
{ label: 'Jesus Maria', value: 'Jesus Maria' },
{ label: 'Jose Leon Suarez', value: 'Jose Leon Suarez' },
{ label: 'Jose Marmol', value: 'Jose Marmol' },
{ label: 'Juan Pujol', value: 'Juan Pujol' },
{ label: 'Justiniano Posse', value: 'Justiniano Posse' },
{ label: 'La Banda', value: 'La Banda' },
{ label: 'La Boca', value: 'La Boca' },
{ label: 'La Calera', value: 'La Calera' },
{ label: 'La Cumbre', value: 'La Cumbre' },
{ label: 'La Falda', value: 'La Falda' },
{ label: 'La Leonesa', value: 'La Leonesa' },
{ label: 'La Lucila', value: 'La Lucila' },
{ label: 'La Madrid', value: 'La Madrid' },
{ label: 'La Pampa', value: 'La Pampa' },
{ label: 'La Para', value: 'La Para' },
{ label: 'La Paz', value: 'La Paz' },
{ label: 'La Plata', value: 'La Plata' },
{ label: 'La Punta', value: 'La Punta' },
{ label: 'La Rioja', value: 'La Rioja' },
{ label: 'La Tablada', value: 'La Tablada' },
{ label: 'La Union', value: 'La Union' },
{ label: 'La Violeta', value: 'La Violeta' },
{ label: 'Laborde', value: 'Laborde' },
{ label: 'Laboulaye', value: 'Laboulaye' },
{ label: 'Laferrere', value: 'Laferrere' },
{ label: 'Laguna Alsina', value: 'Laguna Alsina' },
{ label: 'Lanus', value: 'Lanus' },
{ label: 'Larroque', value: 'Larroque' },
{ label: 'Las Catitas', value: 'Las Catitas' },
{ label: 'Las Flores', value: 'Las Flores' },
{ label: 'Las Flores', value: 'Las Flores' },
{ label: 'Las Heras', value: 'Las Heras' },
{ label: 'Las Perdices', value: 'Las Perdices' },
{ label: 'Las Rosas', value: 'Las Rosas' },
{ label: 'Las Talitas', value: 'Las Talitas' },
{ label: 'Las Varillas', value: 'Las Varillas' },
{ label: 'Lavalle', value: 'Lavalle' },
{ label: 'Leandro N. Alem', value: 'Leandro N. Alem' },
{ label: 'Leones', value: 'Leones' },
{ label: 'Libertad', value: 'Libertad' },
{ label: 'Lima', value: 'Lima' },
{ label: 'Liniers', value: 'Liniers' },
{ label: 'Llavallol', value: 'Llavallol' },
{ label: 'Lobos', value: 'Lobos' },
{ label: 'Lomas de Zamora', value: 'Lomas de Zamora' },
{ label: 'Lomas del Mirador', value: 'Lomas del Mirador' },
{ label: 'Longchamps', value: 'Longchamps' },
{ label: 'Los Antiguos', value: 'Los Antiguos' },
{ label: 'Los Cardales', value: 'Los Cardales' },
{ label: 'Los Molinos', value: 'Los Molinos' },
{ label: 'Los Polvorines', value: 'Los Polvorines' },
{ label: 'Luis Guillon', value: 'Luis Guillon' },
{ label: 'Lujan de Cuyo', value: 'Lujan de Cuyo' },
{ label: 'Luque', value: 'Luque' },
{ label: 'Luzuriaga', value: 'Luzuriaga' },
{ label: 'Lynch', value: 'Lynch' },
{ label: 'Macachin', value: 'Macachin' },
{ label: 'Magdalena', value: 'Magdalena' },
{ label: 'Magdalena', value: 'Magdalena' },
{ label: 'Maggiolo', value: 'Maggiolo' },
{ label: 'Maipu', value: 'Maipu' },
{ label: 'Maipu', value: 'Maipu' },
{ label: 'Manantial', value: 'Manantial' },
{ label: 'Manfredi', value: 'Manfredi' },
{ label: 'Manuel J. Cobo', value: 'Manuel J. Cobo' },
{ label: 'Maquinista Savio', value: 'Maquinista Savio' },
{ label: 'Mar de Ajo', value: 'Mar de Ajo' },
{ label: 'Mar del Plata', value: 'Mar del Plata' },
{ label: 'Mar del Tuyu', value: 'Mar del Tuyu' },
{ label: 'Marcos Juarez', value: 'Marcos Juarez' },
{ label: 'Marcos Paz', value: 'Marcos Paz' },
{ label: 'Margarita', value: 'Margarita' },
{ label: 'Maria Ignacia', value: 'Maria Ignacia' },
{ label: 'Maria Juana', value: 'Maria Juana' },
{ label: 'Mariano Acosta', value: 'Mariano Acosta' },
{ label: 'Mariano J. Haedo', value: 'Mariano J. Haedo' },
{ label: 'Mariano Moreno', value: 'Mariano Moreno' },
{ label: 'Martinez', value: 'Martinez' },
{ label: 'Matheu', value: 'Matheu' },
{ label: 'Mayor Buratovich', value: 'Mayor Buratovich' },
{ label: 'Melincue', value: 'Melincue' },
{ label: 'Mendiolaza', value: 'Mendiolaza' },
{ label: 'Mendoza', value: 'Mendoza' },
{ label: 'Mercedes', value: 'Mercedes' },
{ label: 'Mercedes', value: 'Mercedes' },
{ label: 'Merlo', value: 'Merlo' },
{ label: 'Merlo', value: 'Merlo' },
{ label: 'Minacar', value: 'Minacar' },
{ label: 'Miramar', value: 'Miramar' },
{ label: 'Miramar', value: 'Miramar' },
{ label: 'Monje', value: 'Monje' },
{ label: 'Monte Hermoso', value: 'Monte Hermoso' },
{ label: 'Monteros', value: 'Monteros' },
{ label: 'Montserrat', value: 'Montserrat' },
{ label: 'Moreno', value: 'Moreno' },
{ label: 'Moron', value: 'Moron' },
{ label: 'Morteros', value: 'Morteros' },
{ label: 'Muniz', value: 'Muniz' },
{ label: 'Munro', value: 'Munro' },
{ label: 'Navarro', value: 'Navarro' },
{ label: 'Navarro', value: 'Navarro' },
{ label: 'Necochea', value: 'Necochea' },
{ label: 'Nogoya', value: 'Nogoya' },
{ label: 'Nordelta', value: 'Nordelta' },
{ label: 'Nunez', value: 'Nunez' },
{ label: 'Obera', value: 'Obera' },
{ label: 'Oliva', value: 'Oliva' },
{ label: 'Oliveros', value: 'Oliveros' },
{ label: 'Olivos', value: 'Olivos' },
{ label: 'Oncativo', value: 'Oncativo' },
{ label: 'Open Door', value: 'Open Door' },
{ label: 'Ordonez', value: 'Ordonez' },
{ label: 'Palermo', value: 'Palermo' },
{ label: 'Palmira', value: 'Palmira' },
{ label: 'Palpala', value: 'Palpala' },
{ label: 'Partido de Jose C. Paz', value: 'Partido de Jose C. Paz' },
{ label: 'Pasco', value: 'Pasco' },
{ label: 'Paso del Rey', value: 'Paso del Rey' },
{ label: 'Paternal', value: 'Paternal' },
{ label: 'Pavon', value: 'Pavon' },
{ label: 'Pedernales', value: 'Pedernales' },
{ label: 'Pedro Luro', value: 'Pedro Luro' },
{ label: 'Pellegrini', value: 'Pellegrini' },
{ label: 'Perez', value: 'Perez' },
{ label: 'Pergamino', value: 'Pergamino' },
{ label: 'Perico', value: 'Perico' },
{ label: 'Perito Moreno', value: 'Perito Moreno' },
{ label: 'Piamonte', value: 'Piamonte' },
{ label: 'Pico de Salamanca', value: 'Pico de Salamanca' },
{ label: 'Pico Truncado', value: 'Pico Truncado' },
{ label: 'Pigue', value: 'Pigue' },
{ label: 'Pilar', value: 'Pilar' },
{ label: 'Pinamar', value: 'Pinamar' },
{ label: 'Piquete Cabado', value: 'Piquete Cabado' },
{ label: 'Platanos', value: 'Platanos' },
{ label: 'Plaza Huincul', value: 'Plaza Huincul' },
{ label: 'Plottier', value: 'Plottier' },
{ label: 'Pontevedra', value: 'Pontevedra' },
{ label: 'Portena', value: 'Portena' },
{ label: 'Posadas', value: 'Posadas' },
{ label: 'Pozo del Molle', value: 'Pozo del Molle' },
{ label: 'Presidente Derqui', value: 'Presidente Derqui' },
{ label: 'Puan', value: 'Puan' },
{ label: 'Pueblo San Jose', value: 'Pueblo San Jose' },
{ label: 'Puerto Madryn', value: 'Puerto Madryn' },
{ label: 'Puerto Rico', value: 'Puerto Rico' },
{ label: 'Pueyrredon', value: 'Pueyrredon' },
{ label: 'Punta Alta', value: 'Punta Alta' },
{ label: 'Quilmes', value: 'Quilmes' },
{ label: 'Rada Tilly', value: 'Rada Tilly' },
{ label: 'Rafael Calzada', value: 'Rafael Calzada' },
{ label: 'Rafael Castillo', value: 'Rafael Castillo' },
{ label: 'Rafael Obligado', value: 'Rafael Obligado' },
{ label: 'Rafaela', value: 'Rafaela' },
{ label: 'Ramallo', value: 'Ramallo' },
{ label: 'Ramos Mejia', value: 'Ramos Mejia' },
{ label: 'Ranchos', value: 'Ranchos' },
{ label: 'Rancul', value: 'Rancul' },
{ label: 'Ranelagh', value: 'Ranelagh' },
{ label: 'Rawson', value: 'Rawson' },
{ label: 'Rawson', value: 'Rawson' },
{ label: 'Realico', value: 'Realico' },
{ label: 'Recoleta', value: 'Recoleta' },
{ label: 'Reconquista', value: 'Reconquista' },
{ label: 'Remedios de Escalada', value: 'Remedios de Escalada' },
{ label: 'Resistencia', value: 'Resistencia' },
{ label: 'Retiro', value: 'Retiro' },
{ label: 'Rio Ceballos', value: 'Rio Ceballos' },
{ label: 'Rio Colorado', value: 'Rio Colorado' },
{ label: 'Rio Grande', value: 'Rio Grande' },
{ label: 'Rio Piedras', value: 'Rio Piedras' },
{ label: 'Rio Segundo', value: 'Rio Segundo' },
{ label: 'Rio Tercero', value: 'Rio Tercero' },
{ label: 'Rivadavia', value: 'Rivadavia' },
{ label: 'Rocamora', value: 'Rocamora' },
{ label: 'Rodriguez Pena', value: 'Rodriguez Pena' },
{ label: 'Rojas', value: 'Rojas' },
{ label: 'Roldan', value: 'Roldan' },
{ label: 'Roque Perez', value: 'Roque Perez' },
{ label: 'Rosario', value: 'Rosario' },
{ label: 'Rosas', value: 'Rosas' },
{ label: 'Rufino', value: 'Rufino' },
{ label: 'Sacanta', value: 'Sacanta' },
{ label: 'Saenz Pena', value: 'Saenz Pena' },
{ label: 'Saladillo', value: 'Saladillo' },
{ label: 'Salguero', value: 'Salguero' },
{ label: 'Salsipuedes', value: 'Salsipuedes' },
{ label: 'Salta', value: 'Salta' },
{ label: 'Salto', value: 'Salto' },
{ label: 'Salto Grande', value: 'Salto Grande' },
{ label: 'Sampacho', value: 'Sampacho' },
{ label: 'San Andres', value: 'San Andres' },
{ label: 'San Andres de Giles', value: 'San Andres de Giles' },
{ label: 'San Antonio de Areco', value: 'San Antonio de Areco' },
{ label: 'San Antonio de Arredondo', value: 'San Antonio de Arredondo' },
{ label: 'San Antonio de Obligado', value: 'San Antonio de Obligado' },
{ label: 'San Antonio de Padua', value: 'San Antonio de Padua' },
{ label: 'San Antonio Oeste', value: 'San Antonio Oeste' },
{ label: 'San Benito', value: 'San Benito' },
{ label: 'San Bernardo', value: 'San Bernardo' },
{ label: 'San Carlos de Bolivar', value: 'San Carlos de Bolivar' },
{ label: 'San Cayetano', value: 'San Cayetano' },
{ label: 'San Clemente', value: 'San Clemente' },
{ label: 'San Cristobal', value: 'San Cristobal' },
{ label: 'San Fernando', value: 'San Fernando' },
{ label: 'San Fernando del Valle de Catamarca', value: 'San Fernando del Valle de Catamarca' },
{ label: 'San Francisco', value: 'San Francisco' },
{ label: 'San Francisco de Santa Fe', value: 'San Francisco de Santa Fe' },
{ label: 'San Francisco Solano', value: 'San Francisco Solano' },
{ label: 'San Genaro', value: 'San Genaro' },
{ label: 'San Gregorio', value: 'San Gregorio' },
{ label: 'San Guillermo', value: 'San Guillermo' },
{ label: 'San Isidro', value: 'San Isidro' },
{ label: 'San Isidro de Lules', value: 'San Isidro de Lules' },
{ label: 'San Javier', value: 'San Javier' },
{ label: 'San Jeronimo Norte', value: 'San Jeronimo Norte' },
{ label: 'San Jorge', value: 'San Jorge' },
{ label: 'San Jose', value: 'San Jose' },
{ label: 'San Jose de la Esquina', value: 'San Jose de la Esquina' },
{ label: 'San Juan', value: 'San Juan' },
{ label: 'San Justo', value: 'San Justo' },
{ label: 'San Lorenzo', value: 'San Lorenzo' },
{ label: 'San Luis', value: 'San Luis' },
{ label: 'San Manuel', value: 'San Manuel' },
{ label: 'San Martin', value: 'San Martin' },
{ label: 'San Martin de las Escobas', value: 'San Martin de las Escobas' },
{ label: 'San Miguel', value: 'San Miguel' },
{ label: 'San Miguel del Monte', value: 'San Miguel del Monte' },
{ label: 'San Nicolas', value: 'San Nicolas' },
{ label: 'San Pedro', value: 'San Pedro' },
{ label: 'San Pedro', value: 'San Pedro' },
{ label: 'San Rafael', value: 'San Rafael' },
{ label: 'San Salvador', value: 'San Salvador' },
{ label: 'San Salvador de Jujuy', value: 'San Salvador de Jujuy' },
{ label: 'San Telmo', value: 'San Telmo' },
{ label: 'San Vicente', value: 'San Vicente' },
{ label: 'Sanchez', value: 'Sanchez' },
{ label: 'Santa Clara de Saguier', value: 'Santa Clara de Saguier' },
{ label: 'Santa Elena', value: 'Santa Elena' },
{ label: 'Santa Fe', value: 'Santa Fe' },
{ label: 'Santa Lucia', value: 'Santa Lucia' },
{ label: 'Santa Rita', value: 'Santa Rita' },
{ label: 'Santa Rosa', value: 'Santa Rosa' },
{ label: 'Santa Teresita', value: 'Santa Teresita' },
{ label: 'Santiago del Estero', value: 'Santiago del Estero' },
{ label: 'Santo Tome', value: 'Santo Tome' },
{ label: 'Santos Lugares', value: 'Santos Lugares' },
{ label: 'Sarandi', value: 'Sarandi' },
{ label: 'Sarmiento', value: 'Sarmiento' },
{ label: 'Segui', value: 'Segui' },
{ label: 'Sierra de la Ventana', value: 'Sierra de la Ventana' },
{ label: 'Sierra de los Padres', value: 'Sierra de los Padres' },
{ label: 'Sinsacate', value: 'Sinsacate' },
{ label: 'Suipacha', value: 'Suipacha' },
{ label: 'Sunchales', value: 'Sunchales' },
{ label: 'Tablada', value: 'Tablada' },
{ label: 'Tacuari', value: 'Tacuari' },
{ label: 'Tafi Viejo', value: 'Tafi Viejo' },
{ label: 'Tandil', value: 'Tandil' },
{ label: 'Tapalque', value: 'Tapalque' },
{ label: 'Tapiales', value: 'Tapiales' },
{ label: 'Temperley', value: 'Temperley' },
{ label: 'Teodelina', value: 'Teodelina' },
{ label: 'Thames', value: 'Thames' },
{ label: 'Tigre', value: 'Tigre' },
{ label: 'Tio Pujio', value: 'Tio Pujio' },
{ label: 'Todd', value: 'Todd' },
{ label: 'Tornquist', value: 'Tornquist' },
{ label: 'Tortuguitas', value: 'Tortuguitas' },
{ label: 'Tostado', value: 'Tostado' },
{ label: 'Totoras', value: 'Totoras' },
{ label: 'Trelew', value: 'Trelew' },
{ label: 'Trenque Lauquen', value: 'Trenque Lauquen' },
{ label: 'Tres Arroyos', value: 'Tres Arroyos' },
{ label: 'Trevelin', value: 'Trevelin' },
{ label: 'Tristan Suarez', value: 'Tristan Suarez' },
{ label: 'Tunuyan', value: 'Tunuyan' },
{ label: 'Tupungato', value: 'Tupungato' },
{ label: 'Turdera', value: 'Turdera' },
{ label: 'Ucacha', value: 'Ucacha' },
{ label: 'Uriburu', value: 'Uriburu' },
{ label: 'Ushuaia', value: 'Ushuaia' },
{ label: 'Valle Hermoso', value: 'Valle Hermoso' },
{ label: 'Vedia', value: 'Vedia' },
{ label: 'Veinticinco de Mayo', value: 'Veinticinco de Mayo' },
{ label: 'Venado Tuerto', value: 'Venado Tuerto' },
{ label: 'Vera', value: 'Vera' },
{ label: 'Veronica', value: 'Veronica' },
{ label: 'Viale', value: 'Viale' },
{ label: 'Viamonte', value: 'Viamonte' },
{ label: 'Vicente Lopez', value: 'Vicente Lopez' },
{ label: 'Victoria', value: 'Victoria' },
{ label: 'Victoria', value: 'Victoria' },
{ label: 'Vicuna Mackenna', value: 'Vicuna Mackenna' },
{ label: 'Viedma', value: 'Viedma' },
{ label: 'Villa Aberastain', value: 'Villa Aberastain' },
{ label: 'Villa Adelina', value: 'Villa Adelina' },
{ label: 'Villa Allende', value: 'Villa Allende' },
{ label: 'Villa Alsina', value: 'Villa Alsina' },
{ label: 'Villa Amelia', value: 'Villa Amelia' },
{ label: 'Villa Angela', value: 'Villa Angela' },
{ label: 'Villa Ballester', value: 'Villa Ballester' },
{ label: 'Villa Bosch', value: 'Villa Bosch' },
{ label: 'Villa Canas', value: 'Villa Canas' },
{ label: 'Villa Carlos Paz', value: 'Villa Carlos Paz' },
{ label: 'Villa Constitucion', value: 'Villa Constitucion' },
{ label: 'Villa de Maria', value: 'Villa de Maria' },
{ label: 'Villa de Mayo', value: 'Villa de Mayo' },
{ label: 'Villa del Parque', value: 'Villa del Parque' },
{ label: 'Villa Dolores', value: 'Villa Dolores' },
{ label: 'Villa Dominico', value: 'Villa Dominico' },
{ label: 'Villa Elisa', value: 'Villa Elisa' },
{ label: 'Villa General Belgrano', value: 'Villa General Belgrano' },
{ label: 'Villa Gesell', value: 'Villa Gesell' },
{ label: 'Villa Giardino', value: 'Villa Giardino' },
{ label: 'Villa Huidobro', value: 'Villa Huidobro' },
{ label: 'Villa Insuperable', value: 'Villa Insuperable' },
{ label: 'Villa La Angostura', value: 'Villa La Angostura' },
{ label: 'Villa Las Rosas', value: 'Villa Las Rosas' },
{ label: 'Villa Lugano', value: 'Villa Lugano' },
{ label: 'Villa Luzuriaga', value: 'Villa Luzuriaga' },
{ label: 'Villa Madero', value: 'Villa Madero' },
{ label: 'Villa Maria Grande', value: 'Villa Maria Grande' },
{ label: 'Villa Media Agua', value: 'Villa Media Agua' },
{ label: 'Villa Mercedes', value: 'Villa Mercedes' },
{ label: 'Villa Mercedes', value: 'Villa Mercedes' },
{ label: 'Villa Nueva', value: 'Villa Nueva' },
{ label: 'Villa Nueva', value: 'Villa Nueva' },
{ label: 'Villa Ocampo', value: 'Villa Ocampo' },
{ label: 'Villa Paranacito', value: 'Villa Paranacito' },
{ label: 'Villa Regina', value: 'Villa Regina' },
{ label: 'Villa Robles', value: 'Villa Robles' },
{ label: 'Villa Rosa', value: 'Villa Rosa' },
{ label: 'Villa Trinidad', value: 'Villa Trinidad' },
{ label: 'Villa Urquiza', value: 'Villa Urquiza' },
{ label: 'Villaguay', value: 'Villaguay' },
{ label: 'Vuelta de Obligado', value: 'Vuelta de Obligado' },
{ label: 'Warnes', value: 'Warnes' },
{ label: 'Wheelwright', value: 'Wheelwright' },
{ label: 'Wilde', value: 'Wilde' },
{ label: 'Winifreda', value: 'Winifreda' },
{ label: 'Yerba Buena', value: 'Yerba Buena' },
{ label: 'Zenon Pereyra', value: 'Zenon Pereyra' }
];

export {all_cities};